services:
  simplepysandbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simplepysandbox
    ports:
      - "8000:8000"
    environment:
      - EXECUTION_MODE=conda
      - HOST=0.0.0.0
      - PORT=8000
      - PYTHONPATH=/app
    volumes:
      # 挂载数据目录以持久化环境数据
      - ./data:/app/data
      # 挂载日志目录（如果存在）
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
